### ISSUE TITLE
昨天都好使，今天发现生成歌曲报错，查询歌曲正常

### ISSUE THREAD

**Issue by linxp001** [disingn/sunotoapi#11]
{"error_code":1002,"error_msg":"unexpected status code: 503, response body: {\"detail\": \"Service Unavailable\"}"}

**Comment by leafrainy** [comment]
> {"error_code":1002,"error_msg":"unexpected status code: 503, response body: {"detail": "Service Unavailable"}"}

官方维护，刚开始是生成不了（凌晨1-2点），后来是只有订阅用户可以提交（大概早上7点30我看到的）。现在看木有任何提示了我的工具可以使用~ 建议你重新跑下再看看。
