### ISSUE TITLE
能编译一份ARM的吗？我编译后执行报错了

### ISSUE THREAD

**Issue by itq5** [disingn/sunotoapi#2]
# go build
go: downloading github.com/gofiber/fiber/v2 v2.52.3
go: downloading github.com/spf13/viper v1.18.2
go: downloading github.com/fsnotify/fsnotify v1.7.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/sagikazarmark/slog-shim v0.1.0
go: downloading github.com/spf13/afero v1.11.0
go: downloading github.com/spf13/cast v1.6.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/sys v0.15.0
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/subosito/gotenv v1.6.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.7
go: downloading github.com/pelletier/go-toml/v2 v2.1.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/google/uuid v1.5.0
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/mattn/go-runewidth v0.0.15
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/valyala/fasthttp v1.51.0
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/valyala/tcplisten v1.0.0
go: downloading github.com/klauspost/compress v1.17.0
go: downloading github.com/andybalholm/brotli v1.0.5
root@wkp-pc:~/Work/www/wwwroot/sunotoapi# ls
cfg  config.yaml  fksunoapi  go.mod  go.sum  main.go  models  readme.md  router  serve
# ./fksunoapi 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
fksunoapi/serve.GetSession()
        /root/Work/www/wwwroot/sunotoapi/serve/serve.go:46 +0x4f0
main.init.0()
        /root/Work/www/wwwroot/sunotoapi/main.go:12 +0x20

**Comment by disingn** [comment]
先 go mod tidy 然后再编译

**Comment by itq5** [comment]
> 先 go mod tidy 然后再编译
#  go mod tidy
go: downloading github.com/sagikazarmark/locafero v0.4.0
go: downloading golang.org/x/exp v0.0.0-20230905200255-921286631fa9
go: downloading github.com/sourcegraph/conc v0.3.0
go: downloading github.com/stretchr/testify v1.8.4
go: downloading github.com/frankban/quicktest v1.14.6
go: downloading github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc
go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
go: downloading github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2
go: downloading go.uber.org/multierr v1.9.0
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/kr/pretty v0.3.1
go: downloading go.uber.org/atomic v1.9.0
go: downloading github.com/rogpeppe/go-internal v1.9.0
go: downloading github.com/kr/text v0.2.0



# go build



./fksunoapi 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
fksunoapi/serve.GetSession()
        /root/Work/www/wwwroot/sunotoapi/serve/serve.go:46 +0x4f0
main.init.0()
        /root/Work/www/wwwroot/sunotoapi/main.go:12 +0x20


执行还是报错了

# uname -a
Linux xxxx 6.5.0-17-generic #17-Ubuntu SMP PREEMPT_DYNAMIC Thu Jan 11 14:20:13 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

# go version
go version go1.21.1 linux/arm64

**Comment by disingn** [comment]
你的Client填写正确了吗 这报错显示没拿到对应的 json 响应

**Comment by itq5** [comment]
添加的正确的，需要加“”吗？

**Comment by itq5** [comment]
> 添加的正确的，需要加“”吗？

![image](https://github.com/disingn/sunotoapi/assets/42521985/b42e6879-cbcf-4963-a088-b5f32365b4dd)

**Comment by itq5** [comment]
> > > 添加的正确的，需要加“”吗？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/42521985/317676552-b42e6879-cbcf-4963-a088-b5f32365b4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjAwMTgsIm5iZiI6MTcxMTYxOTcxOCwicGF0aCI6Ii80MjUyMTk4NS8zMTc2NzY1NTItYjQyZTY4NzktY2JjZi00OTYzLWEwODgtYjVmMzIzNjViNGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA5NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTMzMThkNzAwOTNjNmE4MGQ4OGFiZGIwOWZiMzFiMDViN2FkYzAwNTcxYzVmZTZjNmExM2VjYjAzMjFkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0RGUqdztaa7HYxx0tuk5fJL-SF9ZI6yXRPVBhuxUkw)
> 
> 不需要

那确实还是不行，是不是代码里面需要做修正

**Comment by disingn** [comment]
> > > > 添加的正确的，需要加“”吗？
> 
> > > 
> 
> > > 
> 
> > > ![image](https://private-user-images.githubusercontent.com/42521985/317676552-b42e6879-cbcf-4963-a088-b5f32365b4dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjAwMTgsIm5iZiI6MTcxMTYxOTcxOCwicGF0aCI6Ii80MjUyMTk4NS8zMTc2NzY1NTItYjQyZTY4NzktY2JjZi00OTYzLWEwODgtYjVmMzIzNjViNGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA5NTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MTMzMThkNzAwOTNjNmE4MGQ4OGFiZGIwOWZiMzFiMDViN2FkYzAwNTcxYzVmZTZjNmExM2VjYjAzMjFkZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J0RGUqdztaa7HYxx0tuk5fJL-SF9ZI6yXRPVBhuxUkw)
> 
> > 
> 
> > 不需要
> 
> 
> 
> 那确实还是不行，是不是代码里面需要做修正

把yaml配置发一下
