### ISSUE TITLE
能支持多client吗？填入多账号的，轮训使用

### ISSUE THREAD

**Issue by itq5** [disingn/sunotoapi#3]
能支持多client吗？填入多账号的，轮训使用

**Comment by disingn** [comment]
> 能支持多client吗？填入多账号的，轮训使用

不建议这样

**Comment by disingn** [comment]
> 能支持多client吗？填入多账号的，轮训使用

有时间再改吧

**Comment by dcln78** [comment]
有空再加个多账号吧，一天10首不够啊 作者大佬,哈哈

**Comment by disingn** [comment]
> 有空再加个多账号吧，一天10首不够啊 作者大佬,哈哈

建议充钱

**Comment by disingn** [comment]
已支持

**Comment by itq5** [comment]
> 已支持

如何配置的，望大佬指导！
