### ISSUE TITLE
chat格式测试使用问题请教

### ISSUE THREAD

**Issue by sfvsfv** [disingn/sunotoapi#4]
配置参数应该没问题：
<img width="959" alt="image" src="https://github.com/disingn/sunotoapi/assets/62045791/4226b7be-6fd6-4012-9784-c0e3202466fe">

我反向代理到域名，然后到chatbox测试，前端重复生成了三次内容，以及部分空：
<img width="666" alt="image" src="https://github.com/disingn/sunotoapi/assets/62045791/7961415c-91ff-46a3-bf92-912625b394a7">

最终返回结果如下：
<img width="681" alt="image" src="https://github.com/disingn/sunotoapi/assets/62045791/eb92d2cc-7a68-498b-9796-4b2185d28d13">

请问是否chat格式缺少了什么配置还是其他问题呢？

**Comment by sfvsfv** [comment]
官方的语法格式为：
`curl https://api.openai.com/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer $OPENAI_API_KEY"   -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."
      },
      {
        "role": "user",
        "content": "Compose a poem that explains the concept of recursion in programming."
      }
    ]
  }'
`

不知是否我使用错误导致。

**Comment by disingn** [comment]
> 官方的语法格式为：
> 
> `curl https://api.openai.com/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer $OPENAI_API_KEY"   -d '{
> 
>     "model": "gpt-3.5-turbo",
> 
>     "messages": [
> 
>       {
> 
>         "role": "system",
> 
>         "content": "You are a poetic assistant, skilled in explaining complex programming concepts with creative flair."
> 
>       },
> 
>       {
> 
>         "role": "user",
> 
>         "content": "Compose a poem that explains the concept of recursion in programming."
> 
>       }
> 
>     ]
> 
>   }'
> 
> `
> 
> 
> 
> 不知是否我使用错误导致。

nginx反代超时时间设置3分钟以上
