### ISSUE TITLE
status code: 401

### ISSUE THREAD

**Issue by duansix** [disingn/sunotoapi#7]
sendRequest failed, unexpected status code: 401, response body: {"detail": "Unauthorized"}
个人未订阅的账号不能用吗

**Comment by dcln78** [comment]
确实，换了v0.1.4之后，重新换了账号也是这个问题

**Comment by duansix** [comment]
后台看到任务了 并且已经成功了 实际不能返回内容 一直报错sendRequest failed, unexpected status code: 401, response body: {"detail": "Unauthorized"}

**Comment by disingn** [comment]
> 后台看到任务了 并且已经成功了 实际不能返回内容 一直报错sendRequest failed, unexpected status code: 401, response body: {"detail": "Unauthorized"}

正在看

**Comment by disingn** [comment]
已经修复
